import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Link from "next/link";
import useHistoryStore from "../hooks/useHistoryStore";

const Home: NextPage = (props) => {
  const { data: clinics } = trpc.useQuery(["clinics.getAllClinics"]);
  const setClinicId = useHistoryStore((state) => state.setClinicId);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        {clinics?.map((clinic) => {
          return (
            <div key={clinic.id} onClick={() => setClinicId(clinic.id)}>
              <Link
                href={{
                  pathname: `${clinic.name.toLowerCase()}`,
                  // query: { id: clinic.id },
                }}
              >
                {clinic.name}
              </Link>
            </div>
          );
        })}
      </main>
    </>
  );
};

export default Home;
